name: Deploy Develop to Netlify on Push
on:
  push:
    branches:
      - eb-netlify
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # https://github.com/actions/setup-node#usage
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: git submodule update --init --remote
    - name: npm install
      run: npm install
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
    - name: gatsby build
      run: npm run build
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        ALGOLIA_API_KEY:  ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_APP_ID:  ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_INDEX_NAME:  ${{ secrets.ALGOLIA_INDEX_NAME }}
    # Deploy the gatsby build to Netlify
    #- run: npx netlify-cli deploy --dir=public --prod
    # https://github.com/netlify/actions/blob/master/cli/README.md
    - uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswithargs
        args: deploy --dir=public --prod
